# Job used to migrate DB
apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
spec:
  template:
    spec:
      containers:
        - name: rails-server
          image: lessuk/kubernetes-rails-example:latest
          command: ["rails", "db:migrate"]
          envFrom:
            - configMapRef:
                name: env
          env:
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: rails-secrets
                  key: rails_master_key
      restartPolicy: Never
  backoffLimit: 4
