apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      server: rails-app
  template:
    metadata:
      labels:
        server: rails-app
    spec:
      containers:
        - name: rails-app
          image: lessuk/kubernetes-rails-example:latest
          envFrom:
          - configMapRef:
              name: env
          env:
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: rails-secrets
                  key: rails_master_key
          ports:
            - containerPort: 3000