apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      worker: sidekiq-worker
  template:
    metadata:
      labels:
        worker: sidekiq-worker
    spec:
      containers:
        - name: sidekiq-worker
          image: lessuk/kubernetes-rails-example:latest
          command: ["sidekiq"]
          envFrom:
            - configMapRef:
                name: env
          env:
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: rails-secrets
                  key: rails_master_key